"""empty message

Revision ID: 5e1cc2929a6b
Revises: 
Create Date: 2025-08-13 21:26:50.181911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1cc2929a6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('verification_linkedin', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('is_verified')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('verification_linkedin')
        batch_op.drop_column('verification_email')

    # ### end Alembic commands ###
